### ISSUE TITLE
Evilginx2 container error

### ISSUE THREAD

**Issue by xoep** [warhorse/warhorse#7]
Ansible encounters error and stops at evilginx2 role
Error:
fatal: [phish]: FAILED! => {"changed": false, "msg": "Error starting container a9c2d40d3da591d89a23c2cd16015feb1d51cfcf97dc156f9fdf8c956a0605a5: 400 Client Error for http+docker://localhost/v1.41/containers/a9c2d40d3da591d89a23c2cd16015feb1d51cfcf97dc156f9fdf8c956a0605a5/start: Bad Request (\"failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: \"/bin/evilginx -p /phishlets -c /config -t /templates -debug -developer\": stat /bin/evilginx -p /phishlets -c /config -t /templates -debug -developer: no such file or directory: unknown\")"}

**Comment by ralphte** [comment]
This has been fixed
